### ISSUE TITLE
DW1707 Bluetooth can work?

### ISSUE THREAD

**Issue by willin** [SinhLv/Dell-Ins-14-5447-hackintosh#1]
DW1707 的蓝牙模块是否能正常工作，用什么 kext 驱动？

**Comment by SinhLv** [comment]
Yep, use BTFirmwareUploader kext from insanelymac, then yu bluetooth can work properly

**Comment by willin** [comment]
where's BTFirmwareUploader.kext?

**Comment by willin** [comment]
bcm:

<img width="274" alt="qq20181227-164336 2x" src="https://user-images.githubusercontent.com/1890238/50473092-94872380-09f6-11e9-9701-2f65559ccae0.png">

previous achi patch 

<img width="399" alt="qq20181227-164320 2x" src="https://user-images.githubusercontent.com/1890238/50473105-9ea92200-09f6-11e9-90fb-24e5d4bb478c.png">

both not work.

<img width="813" alt="qq20181227-164428 2x" src="https://user-images.githubusercontent.com/1890238/50473127-b2ed1f00-09f6-11e9-92eb-1056d78b50d9.png">

**Comment by SinhLv** [comment]
Sorry but plz read my updated Readme, I changed wireless again.
