### ISSUE TITLE
How did you make your DW1820A work in OS X?

### ISSUE THREAD

**Issue by lwtdzh** [SinhLv/Dell-Ins-14-5447-hackintosh#4]
我正在使用戴尔9350，dw1820a让人十分头疼，而DW1707经常重启网卡就没了，还是想换回1820A，不知你用了哪些驱动，可以分享下么？谢谢~

**Comment by lwtdzh** [comment]
Eh, It makes me feel bad when using DW1820A, and DW1707 will usually become invalid after restart. Can you share your drivers for DW1820A with me? Thank you very much`~!!

**Comment by SinhLv** [comment]
You can explore this git to get it for your own or take a look to this original guide from tonymacx86
https://www.tonymacx86.com/threads/broadcom-wifi-bluetooth-guide.242423/
